services:
  # reference: https://sanidhya235.medium.com/introduction-to-minio-193e8523a4a8
  # reference: https://mlflow.org/docs/latest/tracking/tutorials/remote-server.html
  # reference: https://blog.min.io/setting-up-a-development-machine-with-mlflow-and-minio/
  db:
    restart: always
    image: postgres:latest
    container_name: mlflow_db
    expose:
      - "${PG_PORT}:${PG_PORT}"
    # networks:
    #   - backend
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "${PG_PORT}", "-U", "${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

  s3:
    image: quay.io/minio/minio
    container_name: mlflow_minio
    volumes:
      - ./minio_data:/data # mount container 'data' directory to 'data' directory of local machine in case of outage.
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    # networks:
    #   - frontend
    #   - backend
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ADDRESS=${MINIO_ADDRESS}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_STORAGE_USE_HTTPS=${MINIO_STORAGE_USE_HTTPS}
      - MINIO_CONSOLE_ADDRESS=${MINIO_CONSOLE_ADDRESS}
    command: minio server /data --address ${MINIO_ADDRESS} --console-address ${MINIO_CONSOLE_ADDRESS}
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5

  minio-create-bucket: # possible solution; https://github.com/minio/mc/issues/3421#issuecomment-699597252
    image: minio/mc
    container_name: create-minio-bucket
    # networks:
    #   - backend
    depends_on:
      s3:
        condition: service_healthy
    network_mode: service:s3
    entrypoint: /bin/sh
    command: -c "
      mc config host add myminio http://localhost:${MINIO_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_ACCESS_KEY} &&
      mc mb myminio/wemadeitbucket
      "

    # entrypoint: >
    #   bash -c "
    #   mc alias set minio http://127.0.0.1:${MINIO_CONSOLE_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_ACCESS_KEY} &&
    #   if ! mc ls minio | grep --quiet marcusbucket; then
    #     mc mb minio/marcusbucket
    #   else
    #     echo 'bucket already exists'
    #   fi
    #   "

  tracking_server:
    restart: always
    build: ./mlflow # build container based on Dockerfile in mlflow directory
    image: mlflow_server
    container_name: mlflow_server
    depends_on:
      - db
    ports:
      - "${MLFLOW_PORT}:5000"
    # networks:
    #   - frontend
    #   - backend
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=http://s3:${MINIO_PORT}
      - MLFLOW_S3_IGNORE_TLS=true
    command: >
      mlflow server
      --backend-store-uri postgresql://${PG_USER}:${PG_PASSWORD}@db:${PG_PORT}/${PG_DATABASE}
      --host 0.0.0.0
      --serve-artifacts
      --artifacts-destination s3://${MLFLOW_BUCKET_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MLFLOW_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3
# networks:
#   frontend:
#     driver: bridge
#   backend:
#     driver: bridge
